### ISSUE TITLE
건의사항-로그인여부체크해서 관리자인 경우만 동작하도록.

### ISSUE THREAD

**Issue by eondcom** [wstackme/wst_rdbl_to_admin#1]
1. 만약 로그인되어있다면, 관리자를 체크해서
관리자인 경우만 해당 스크립트가 동작하도록 하면 더 좋지 않을까 싶어요.

1. 만약 로그인되어있지 않으면 기존대로 동작하구요.

**Comment by nemo9l** [comment]
건의 감사합니다. 업데이트 하도록 하겠습니다.
